name = "spino-gambinojeux-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinojeux.fr"
HMAC_KEY = "b20a786fa924bf5165dc554b8b13ae1458404c61ce4ab6925a5c754096d739b0"
COOKIE_NAME = "y5a"
PLAY_PATH = "try"
BUTTON_ID = "p36ddd1cdfe1eb31f9c1aedc83d4e7eaa"
GATE_SALT = "d7cda27078b507f1"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "xuf8"
CTA_SELECTOR = ".play-button"
